# Module: blinky_zybo_z7
# File:   out_generate.tcl
# Date:   16:17 25/05/2020
# DO NOT MODIFY THIS FILE; AUTOMATICALLY GENERATED BY INTERFACER

####### Checkpoint for mode_a #######

create_project -part xc7z020-clg400 -in_memory

read_ip None

read_verilog { rtl/top_0.v rtl/blink.v } 
read_xdc ['rtl/zybo.xdc']

synth_design -top blinky_zybo_z7 -mode out_of_context 
write_checkpoint mode_a.dcp --force

close_project

####### Checkpoint for mode_b #######

create_project -part xc7z020-clg400 -in_memory

read_ip None

read_verilog { rtl/top_1.v rtl/blink.v } 
read_xdc ['rtl/zybo.xdc']

synth_design -top blinky_zybo_z7 -mode out_of_context 
write_checkpoint mode_b.dcp --force

close_project

