/*
* Module: blinky_zybo_z7
* File:   out_wrapper.v
* Date:   21:56 22/05/2020
* DO NOT MODIFY THIS FILE; AUTOMATICALLY GENERATED BY INTERFACER
*/

module blinky_zybo_z7_wrapper
(

);


  blinky_zybo_z7
  blackbox
  (
  );


endmodule
