/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* src = "rtl/blink.v:1" *)
module \$paramod\blinky\clk_freq_hz=125000000 (clk, q);
  (* src = "rtl/blink.v:8" *)
  wire [26:0] _000_;
  (* src = "rtl/blink.v:8" *)
  wire _001_;
  (* src = "rtl/blink.v:9" *)
  (* unused_bits = "27" *)
  wire [31:0] _002_;
  wire [12:0] _003_;
  wire [6:0] _004_;
  wire [2:0] _005_;
  wire [1:0] _006_;
  wire [26:0] _007_;
  wire _008_;
  (* src = "rtl/blink.v:11" *)
  wire _009_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "26" *)
  wire [31:0] _010_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _011_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _012_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _013_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _014_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _015_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _016_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _017_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _018_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _019_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _020_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _021_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _022_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _023_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _024_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _025_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _026_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _027_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _028_;
  (* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)
  wire _029_;
  (* src = "rtl/blink.v:3" *)
  input clk;
  (* init = 27'h0000000 *)
  (* src = "rtl/blink.v:6" *)
  reg [26:0] count = 27'h0000000;
  (* src = "rtl/blink.v:4" *)
  output q;
  reg q;
  assign _003_[0] = _002_[0] |(* src = "rtl/blink.v:10" *)  _007_[1];
  assign _003_[1] = _007_[2] |(* src = "rtl/blink.v:10" *)  _007_[3];
  assign _003_[2] = _007_[4] |(* src = "rtl/blink.v:10" *)  _007_[5];
  assign _003_[3] = count[6] |(* src = "rtl/blink.v:10" *)  count[7];
  assign _003_[4] = _007_[8] |(* src = "rtl/blink.v:10" *)  count[9];
  assign _003_[5] = count[10] |(* src = "rtl/blink.v:10" *)  _007_[11];
  assign _003_[6] = _007_[12] |(* src = "rtl/blink.v:10" *)  count[13];
  assign _003_[7] = _007_[14] |(* src = "rtl/blink.v:10" *)  count[15];
  assign _003_[8] = _007_[16] |(* src = "rtl/blink.v:10" *)  _007_[17];
  assign _003_[9] = count[18] |(* src = "rtl/blink.v:10" *)  count[19];
  assign _003_[10] = _007_[20] |(* src = "rtl/blink.v:10" *)  _007_[21];
  assign _003_[11] = _007_[22] |(* src = "rtl/blink.v:10" *)  count[23];
  assign _003_[12] = _007_[24] |(* src = "rtl/blink.v:10" *)  _007_[25];
  assign _004_[0] = _003_[0] |(* src = "rtl/blink.v:10" *)  _003_[1];
  assign _004_[1] = _003_[2] |(* src = "rtl/blink.v:10" *)  _003_[3];
  assign _004_[2] = _003_[4] |(* src = "rtl/blink.v:10" *)  _003_[5];
  assign _004_[3] = _003_[6] |(* src = "rtl/blink.v:10" *)  _003_[7];
  assign _004_[4] = _003_[8] |(* src = "rtl/blink.v:10" *)  _003_[9];
  assign _004_[5] = _003_[10] |(* src = "rtl/blink.v:10" *)  _003_[11];
  assign _004_[6] = _003_[12] |(* src = "rtl/blink.v:10" *)  _007_[26];
  assign _005_[0] = _004_[0] |(* src = "rtl/blink.v:10" *)  _004_[1];
  assign _005_[1] = _004_[2] |(* src = "rtl/blink.v:10" *)  _004_[3];
  assign _005_[2] = _004_[4] |(* src = "rtl/blink.v:10" *)  _004_[5];
  assign _006_[0] = _005_[0] |(* src = "rtl/blink.v:10" *)  _005_[1];
  assign _006_[1] = _005_[2] |(* src = "rtl/blink.v:10" *)  _004_[6];
  assign _008_ = _006_[0] |(* src = "rtl/blink.v:10" *)  _006_[1];
  assign _009_ = ~(* src = "rtl/blink.v:11" *) q;
  assign _000_[11] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[11] : 1'h0;
  assign _000_[12] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[12] : 1'h0;
  assign _000_[13] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[13] : 1'h0;
  assign _000_[14] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[14] : 1'h0;
  assign _000_[15] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[15] : 1'h0;
  assign _000_[16] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[16] : 1'h0;
  assign _000_[17] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[17] : 1'h0;
  assign _000_[18] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[18] : 1'h0;
  assign _000_[19] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[19] : 1'h0;
  assign _000_[20] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[20] : 1'h0;
  assign _000_[21] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[21] : 1'h0;
  assign _000_[22] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[22] : 1'h0;
  assign _000_[23] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[23] : 1'h0;
  assign _000_[24] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[24] : 1'h0;
  assign _000_[25] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[25] : 1'h0;
  assign _000_[26] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[26] : 1'h0;
  assign _001_ = _008_ ? (* src = "rtl/blink.v:10" *) q : _009_;
  assign _000_[0] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[0] : 1'h0;
  assign _000_[1] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[1] : 1'h0;
  assign _000_[2] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[2] : 1'h0;
  assign _000_[3] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[3] : 1'h0;
  assign _000_[4] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[4] : 1'h0;
  assign _000_[5] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[5] : 1'h0;
  assign _000_[6] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[6] : 1'h0;
  assign _000_[7] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[7] : 1'h0;
  assign _000_[8] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[8] : 1'h0;
  assign _000_[9] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[9] : 1'h0;
  assign _000_[10] = _008_ ? (* src = "rtl/blink.v:10" *) _002_[10] : 1'h0;
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      q <= _001_;
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[0] <= _000_[0];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[1] <= _000_[1];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[2] <= _000_[2];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[3] <= _000_[3];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[4] <= _000_[4];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[5] <= _000_[5];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[6] <= _000_[6];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[7] <= _000_[7];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[8] <= _000_[8];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[9] <= _000_[9];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[10] <= _000_[10];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[11] <= _000_[11];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[12] <= _000_[12];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[13] <= _000_[13];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[14] <= _000_[14];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[15] <= _000_[15];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[16] <= _000_[16];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[17] <= _000_[17];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[18] <= _000_[18];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[19] <= _000_[19];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[20] <= _000_[20];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[21] <= _000_[21];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[22] <= _000_[22];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[23] <= _000_[23];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[24] <= _000_[24];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[25] <= _000_[25];
  (* src = "rtl/blink.v:8" *)
  always @(posedge clk)
      count[26] <= _000_[26];
  assign _007_[1] = count[1] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[2] = count[2] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[3] = count[3] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[4] = count[4] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[5] = count[5] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[8] = count[8] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[11] = count[11] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[12] = count[12] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[14] = count[14] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[16] = count[16] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[17] = count[17] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[20] = count[20] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[21] = count[21] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[22] = count[22] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[24] = count[24] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[25] = count[25] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _007_[26] = count[26] ^(* src = "rtl/blink.v:10" *)  1'h1;
  assign _002_[1] = count[1] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  count[0];
  assign _002_[2] = count[2] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[1];
  assign _002_[3] = count[3] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[2];
  assign _002_[4] = count[4] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[3];
  assign _002_[5] = count[5] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[4];
  assign _002_[6] = count[6] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[5];
  assign _002_[7] = count[7] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[6];
  assign _002_[8] = count[8] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[7];
  assign _002_[9] = count[9] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[8];
  assign _002_[10] = count[10] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[9];
  assign _002_[11] = count[11] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[10];
  assign _002_[12] = count[12] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[11];
  assign _002_[13] = count[13] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[12];
  assign _002_[14] = count[14] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[13];
  assign _002_[15] = count[15] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[14];
  assign _002_[16] = count[16] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[15];
  assign _002_[17] = count[17] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[16];
  assign _002_[18] = count[18] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[17];
  assign _002_[19] = count[19] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[18];
  assign _002_[20] = count[20] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[19];
  assign _002_[21] = count[21] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[20];
  assign _002_[22] = count[22] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[21];
  assign _002_[23] = count[23] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[22];
  assign _002_[24] = count[24] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[23];
  assign _002_[25] = count[25] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[24];
  assign _002_[26] = count[26] ^(* src = "rtl/blink.v:9|<techmap.v>:263" *)  _010_[25];
  assign _002_[0] = count[0] ^(* src = "rtl/blink.v:9|<techmap.v>:262" *)  1'h1;
  assign _010_[1] = count[1] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:221" *)  count[0];
  assign _010_[3] = _011_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:221" *)  _010_[1];
  assign _010_[7] = _023_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:221" *)  _010_[3];
  assign _010_[15] = _028_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:221" *)  _010_[7];
  assign _011_ = count[3] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[2];
  assign _012_ = count[5] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[4];
  assign _013_ = count[7] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[6];
  assign _014_ = count[9] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[8];
  assign _015_ = count[11] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[10];
  assign _016_ = count[13] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[12];
  assign _017_ = count[15] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[14];
  assign _018_ = count[17] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[16];
  assign _019_ = count[19] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[18];
  assign _020_ = count[21] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[20];
  assign _021_ = count[23] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[22];
  assign _022_ = count[25] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  count[24];
  assign _023_ = _013_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  _012_;
  assign _024_ = _015_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  _014_;
  assign _025_ = _017_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  _016_;
  assign _026_ = _019_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  _018_;
  assign _027_ = _021_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  _020_;
  assign _028_ = _025_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  _024_;
  assign _029_ = _027_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:222" *)  _026_;
  assign _010_[23] = _029_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[15];
  assign _010_[11] = _024_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[7];
  assign _010_[19] = _026_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[15];
  assign _010_[5] = _012_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[3];
  assign _010_[9] = _014_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[7];
  assign _010_[13] = _016_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[11];
  assign _010_[17] = _018_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[15];
  assign _010_[21] = _020_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[19];
  assign _010_[25] = _022_ &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[23];
  assign _010_[2] = count[2] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[1];
  assign _010_[4] = count[4] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[3];
  assign _010_[6] = count[6] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[5];
  assign _010_[8] = count[8] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[7];
  assign _010_[10] = count[10] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[9];
  assign _010_[12] = count[12] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[11];
  assign _010_[14] = count[14] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[13];
  assign _010_[16] = count[16] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[15];
  assign _010_[18] = count[18] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[17];
  assign _010_[20] = count[20] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[19];
  assign _010_[22] = count[22] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[21];
  assign _010_[24] = count[24] &(* src = "rtl/blink.v:9|<techmap.v>:260|<techmap.v>:229" *)  _010_[23];
  assign _002_[31:28] = 4'h0;
  assign { _007_[23], _007_[19:18], _007_[15], _007_[13], _007_[10:9], _007_[7:6], _007_[0] } = { count[23], count[19:18], count[15], count[13], count[10:9], count[7:6], _002_[0] };
  assign { _010_[31:26], _010_[0] } = { 5'h00, _002_[27], count[0] };
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/top.v:1" *)
module blinky_zybo_z7(clk, rst, ce, fatr, TREADY, tdata, thing);
  (* src = "rtl/top.v:8" *)
  output [9:4] TREADY;
  (* src = "rtl/top.v:6" *)
  input ce;
  (* src = "rtl/top.v:4" *)
  input clk;
  (* src = "rtl/top.v:7" *)
  input [1:0] fatr;
  (* src = "rtl/top.v:5" *)
  input rst;
  (* src = "rtl/top.v:9" *)
  input [9:4] tdata;
  (* src = "rtl/top.v:10" *)
  input [9:4] thing;
endmodule
